USE [master]
GO
/****** Object:  Database [LojaDB]    Script Date: 18/01/2021 12:39:44 ******/
CREATE DATABASE [LojaDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LojaDB', FILENAME = N'D:\Programas\SQL Server 2019\SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\LojaDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LojaDB_log', FILENAME = N'D:\Programas\SQL Server 2019\SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\LojaDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [LojaDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LojaDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LojaDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LojaDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LojaDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LojaDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LojaDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [LojaDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LojaDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LojaDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LojaDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LojaDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LojaDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LojaDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LojaDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LojaDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LojaDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [LojaDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LojaDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LojaDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LojaDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LojaDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LojaDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LojaDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LojaDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [LojaDB] SET  MULTI_USER 
GO
ALTER DATABASE [LojaDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LojaDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LojaDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LojaDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [LojaDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [LojaDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [LojaDB] SET QUERY_STORE = OFF
GO
USE [LojaDB]
GO
/****** Object:  User [DESKTOP-0S9KD9N\Tesla]    Script Date: 18/01/2021 12:39:44 ******/
CREATE USER [DESKTOP-0S9KD9N\Tesla] FOR LOGIN [DESKTOP-0S9KD9N\Tesla] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [DESKTOP-0S9KD9N\Tesla]
GO
/****** Object:  Table [dbo].[Compra]    Script Date: 18/01/2021 12:39:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Compra](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Produto_id] [int] NOT NULL,
	[Qtde_comprada] [int] NOT NULL,
 CONSTRAINT [PK_Compra] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Produto]    Script Date: 18/01/2021 12:39:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Produto](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [nvarchar](255) NOT NULL,
	[Valor_unitario] [float] NOT NULL,
	[Qtde_estoque] [int] NOT NULL,
	[Data_ultima_venda] [varchar](255) NULL,
	[Valor_ultima_venda] [float] NULL,
 CONSTRAINT [PK_Produto] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [LojaDB] SET  READ_WRITE 
GO
